repos:
  - repo: local
    hooks:
      - id: generate-pdf
        name: Generate PDF Resume
        entry: ./scripts/generate-pdf.sh
        language: script
        files: '(index\.html|pdf-styles\.css)$'
        pass_filenames: false

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-added-large-files

  -   repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0
      hooks:
      -   id: prettier
          types_or: [html, css, javascript]
