name: Generate PDF Resume

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
      - 'pdf-styles.css'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc weasyprint

      - name: Generate PDF
        run: |
          pandoc index.html -o assets/maria-tzanidaki-resume.pdf --pdf-engine=weasyprint --css=pdf-styles.css

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add assets/maria-tzanidaki-resume.pdf
          git diff --quiet && git diff --staged --quiet || git commit -m "Update PDF resume"
          git push
