name: Resume Website Workflow

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write  # Needed for updating PDF
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Generate PDF resume
      - name: Install PDF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc weasyprint

      - name: Generate PDF
        run: |
          pandoc index.html -o assets/maria-tzanidaki-resume.pdf --pdf-engine=weasyprint --css=pdf-styles.css

      # Commit updated PDF if changed
      - name: Commit PDF if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add assets/maria-tzanidaki-resume.pdf
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update PDF resume" && git push)

      # Deploy to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
